version: 2.1
orbs:
  node: circleci/node:12.16.2-buster
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm run lint
            - run: npm test
workflows:
    build-and-test:
      jobs:
        - build-and-test
